name: _http_client
description: Internal package to create platform-appropriate HTTP clients.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.1.2

  ssl_certificates:
    path: ../ssl_certificates

dev_dependencies:
  lints: ^6.0.0
