name: webtrit_signaling
description: Dart library for WebTrit Core Signalling.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  equatable: ^2.0.7
  logging: ^1.3.0
  logging_appenders: ^1.4.0+1
  meta: any
  web_socket_channel: ^3.0.3

  _web_socket_channel:
    path: ../_web_socket_channel

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
