name: webtrit_signaling
description: WebTrit Signalling clinet.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.18.0
