name: webtrit_signaling
description: WebTrit Signalling client.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  logging: ^1.1.0
  logging_appenders: ^1.0.0
  meta: ^1.8.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
