name: webtrit_signaling
description: WebTrit Signalling clinet.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  logging: ^1.1.0
  logging_appenders: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
