name: webtrit_signaling
description: Dart library for WebTrit Core Signalling.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  logging: ^1.2.0
  logging_appenders: ^1.1.0
  meta: ^1.9.1
  web_socket_channel: ^2.4.0

  _web_socket_channel:
    path: ../_web_socket_channel

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
