name: webtrit_signaling
description: WebTrit Signalling clinet.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  logging: ^1.0.2
  logging_appenders: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
