name: _web_socket_channel
description: Internal package to create platform-appropriate WS clients..
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
