name: _web_socket_channel
description: Internal package to create platform-appropriate WS clients..
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  # stick to specific version, because following version move to incompatible with current implementation pkg:web
  # (https://pub.dev/packages/web_socket_channel/changelog#241)
  web_socket_channel: 2.4.0

dev_dependencies:
  lints: ^3.0.0
