name: store_info_extractor
description: Library to extract/get the application info from Apple App Store and/or Google Play Store.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  pub_semver: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
