name: store_info_extractor
description: Library to extract/get the application info from Apple App Store and/or Google Play Store.
version: 1.0.0

environment:
  sdk: ^3.8.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
