name: janus_client
version: 0.0.1
description: Janus WebRTC Server websocket clinet.
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logging: ^0.11.4

dev_dependencies:
  test: ^1.14.2
  mockito: ^4.1.1
