flutter_launcher_icons:
  android: true
  image_path_android: "tool/assets/launcher_icons/android.png"
  min_sdk_android: 23
  adaptive_icon_background: "#123752"
  adaptive_icon_foreground: "tool/assets/launcher_icons/ic_foreground.png"
  ios: true
  image_path_ios: "tool/assets/launcher_icons/ios.png"
  web:
    generate: true
    image_path: "tool/assets/launcher_icons/web.png"
    background_color: "#FFFFFF"
    theme_color: "#F3F5F6"
