name: webtrit_api
description: Dart library for WebTrit Core API.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: any
  pub_semver: ^2.1.4

  _http_client:
    path: ../_http_client

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.9
