name: webtrit_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  lints: ^1.0.1
  test: ^1.19.2
