name: webtrit_api
description: Dart library for WebTrit Core API.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.1.2
  json_annotation: ^4.9.0
  meta: any
  pub_semver: ^2.1.4
  logging: ^1.2.0

  _http_client:
    path: ../_http_client

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.2
  mocktail: ^1.0.4

