name: webtrit_api
description: Dart library for WebTrit Core API.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  freezed_annotation: ^3.1.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  meta: any
  pub_semver: ^2.2.0
  logging: ^1.3.0

  _http_client:
    path: ../_http_client

dev_dependencies:
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.26.3
  mocktail: ^1.0.4

