name: webtrit_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
  pedantic: ^1.11.1
  test: ^1.18.0
