name: webtrit_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  meta: ^1.8.0
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.1
  test: ^1.22.0
