name: screenshots
description: WebTrit Phone screenshots application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  bloc_test: ^9.1.3
  clock: ^1.1.1
  device_info_plus: ^9.0.1
  flutter_bloc: ^8.1.2
  go_router: ^7.1.1
  mocktail: ^0.3.0

  webtrit_phone:
    path: ..

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/primary_onboardin_logo.svg
    - assets/logoIconTemplateImage.png
    - assets/login/
    - assets/ringtones/
